filter:
    excluded_paths:
        - 'tests/*'
        - 'spec/*'
checks:
    php:
        code_rating: true
        duplication: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            around_operators:
                additive: false
                concatenation: true
build:
    tests:
        override:
            -
                command: "composer run-tests"
                coverage:
                    file: 'build/tmp/coverage.xml'
                    format: 'clover'
