filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            around_operators:
                additive: false
                concatenation: true
build: true

